[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = "0.32.0"
itertools = "0.14.0"
petgraph = "0.8.3"
z3 = { version = "0.19.7", features = ["gh-release"] }

[lints.rust]
# unused = "allow"
